"""intial migration

Revision ID: 836ae2e8c66c
Revises: 
Create Date: 2025-12-28 10:55:05.769672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '836ae2e8c66c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop objects that depend on 'test1' first
    op.execute("DROP VIEW IF EXISTS test1_view")
    # Remove foreign key constraint on test2 that references test1
    op.drop_constraint("test2_refer_fkey", "test2", type_="foreignkey")
    # Now it's safe to drop dependent tables
    op.drop_table('test2')
    op.drop_table('test1')
    op.drop_table('sample_table')
    op.drop_table('hero')
    op.drop_index(op.f('ix_user_user_name'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    op.create_index(op.f('ix_user_user_name'), 'user', ['user_name'], unique=True)
    op.create_table('hero',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('secret_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('hero_pkey'))
    )
    op.create_table('sample_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sample_table_pkey')),
    sa.UniqueConstraint('user_name', name=op.f('sample_table_user_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('test2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('refer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['refer'], ['test1.id'], name=op.f('test2_refer_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('test2_pkey'))
    )
    op.create_table('test1',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fav_num', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test1_pkey'))
    )
    # ### end Alembic commands ###
