"""added booktaglink table

Revision ID: a1c0b7922b5e
Revises: 1b31b47a626c
Create Date: 2026-02-04 16:11:51.157887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a1c0b7922b5e'
down_revision: Union[str, Sequence[str], None] = '1b31b47a626c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_tag_links',
    sa.Column('book_uid', sa.Uuid(), nullable=False),
    sa.Column('tag_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['book_uid'], ['books.uid'], ),
    sa.ForeignKeyConstraint(['tag_uid'], ['tags.uid'], ),
    sa.PrimaryKeyConstraint('book_uid', 'tag_uid')
    )
    op.create_index(op.f('ix_book_tag_links_book_uid'), 'book_tag_links', ['book_uid'], unique=False)
    op.create_index(op.f('ix_book_tag_links_tag_uid'), 'book_tag_links', ['tag_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_tag_links_tag_uid'), table_name='book_tag_links')
    op.drop_index(op.f('ix_book_tag_links_book_uid'), table_name='book_tag_links')
    op.drop_table('book_tag_links')
    # ### end Alembic commands ###
